import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import React, { useState, useEffect } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css'
import { Card,Button } from 'react-bootstrap';

let gamesMap


export default function Home() {
const [games,setGames] = useState()

useEffect(() => 
axios.get('/api/try')
.then((result)=>{
setGames(result.data.data)
})
.catch((err)=>{
console.log(err)
})
, [])

console.log(games)

if(games !== undefined){
  gamesMap = games.map((game,index)=>{
  return(
    <div key={game.index} className="col-lg-3 col-12 my-3">
      <Card>
        <Card.Img variant="top" src={game.thumbnail} className={styles.cardImg} />
        <Card.Body className={styles.fade}>
        <Card.Title>{game.title}</Card.Title>
        <Card.Text>
        {game.description}
        </Card.Text>
        </Card.Body>
        <Button variant={game.status === "Active" ? "success" : "red"} href={game.open_giveaway} className={game.status !== "Active" ? "disabled" : ""}>
        {game.status}
        </Button>
      </Card>
    </div>
  )
})
}else{
  gamesMap = 
  <h1 className={styles.title}>
  loading...
  </h1>
}
return (
    <div className={styles.container}>
      <Head>
        <title>FreeGA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        FreeGA
      </header>
      <main className={styles.main}>
        <div className="container">
          <div className="row">
            {gamesMap}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/alescofet"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Alex Escofet
        </a>
      </footer>
    </div>
  )
}
