import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import React, { useState, useEffect } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css'
import { Card,Button } from 'react-bootstrap';

let gamesMap


export default function Home() {
const [games,setGames] = useState()

useEffect(() => 
axios.get('/api/try')
.then((result)=>{
setGames(result.data.data)
})
.catch((err)=>{
console.log(err)
})
, [])

console.log(games)

if(games !== undefined){
  gamesMap = games.map((game,index)=>{
  return(
    <div key={game.index} className="col-lg-3 col-12">
      <Card>
        <Card.Img variant="top" src={game.image} />
        <Card.Body>
        <Card.Title>{game.title}</Card.Title>
        <Card.Text className={styles.fade}>
        {game.description}
        </Card.Text>

        <Button variant={game.status === "Active" ? "success" : "red"}>{game.status}</Button>
        </Card.Body>
      </Card>
    </div>
  )
})
}else{
  gamesMap = 
  <h1 className={styles.title}>
  loading...
  </h1>
}
return (
    <div className={styles.container}>
      <Head>
        <title>Free Games and Giveaways</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="container">
          <div className="row">
            {gamesMap}
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/alescofet"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Alex Escofet
        </a>
      </footer>
    </div>
  )
}
